# Generated by Django 3.0.5 on 2020-04-10 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20200410_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user',
            new_name='userr',
        ),
    ]
