# Generated by Django 3.0.5 on 2020-04-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_cupon_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupon',
            name='cena_od_ktorej_dziala',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cupon',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
