# Generated by Django 3.0.5 on 2020-04-14 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_auto_20200413_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cupon',
            old_name='cena_od_ktorej_dziala',
            new_name='cena',
        ),
    ]
