# Generated by Django 3.0.5 on 2020-04-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_auto_20200414_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='odebrana',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='w_trakcie_dostarczania',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='zadanie_zwrotu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='zwrot',
            field=models.BooleanField(default=False),
        ),
    ]
