# Generated by Django 3.0.5 on 2020-04-15 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_auto_20200415_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.Cupon'),
        ),
    ]
