# Generated by Django 3.0.5 on 2020-04-15 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_auto_20200415_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryCupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupon_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Cupon')),
            ],
        ),
    ]
