# Generated by Django 3.0.5 on 2020-04-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_item_dostepna_ilosc'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rozmiar',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=3, null=True),
        ),
    ]
