# Generated by Django 3.0.5 on 2020-04-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0028_item_rozmiar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='dostepna_ilosc',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
