# Generated by Django 3.0.5 on 2020-04-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0029_auto_20200420_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rozmiar',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=3, null=True),
        ),
    ]
