# Generated by Django 3.0.5 on 2020-04-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0030_auto_20200420_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='dostepna_ilosc',
        ),
        migrations.AddField(
            model_name='item',
            name='dostepna_ilosc_l',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='dostepna_ilosc_m',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='dostepna_ilosc_s',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='dostepna_ilosc_xl',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='dostepna_ilosc_xxl',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
