# Generated by Django 3.0.5 on 2020-04-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0033_auto_20200420_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dostepna_ilosc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
