# Generated by Django 3.0.5 on 2020-04-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0034_item_dostepna_ilosc'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rozmiar',
            field=models.BooleanField(default=False),
        ),
    ]
