# Generated by Django 3.0.5 on 2020-04-21 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0036_auto_20200421_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemWariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('klucz', models.CharField(max_length=100)),
                ('wartosc', models.CharField(max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Item')),
            ],
        ),
    ]
