# Generated by Django 3.0.5 on 2020-04-21 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0038_auto_20200421_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='dostepna_ilosc',
        ),
        migrations.RemoveField(
            model_name='item',
            name='dostepna_ilosc_l',
        ),
        migrations.RemoveField(
            model_name='item',
            name='dostepna_ilosc_m',
        ),
        migrations.RemoveField(
            model_name='item',
            name='dostepna_ilosc_s',
        ),
        migrations.RemoveField(
            model_name='item',
            name='dostepna_ilosc_xl',
        ),
        migrations.RemoveField(
            model_name='item',
            name='dostepna_ilosc_xxl',
        ),
        migrations.RemoveField(
            model_name='item',
            name='rozmiar',
        ),
    ]
