# Generated by Django 3.0.5 on 2020-04-21 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0039_auto_20200421_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemWariant2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('ilosc', models.IntegerField(null=True)),
                ('itemwariant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.ItemWariant')),
            ],
        ),
    ]
