# Generated by Django 3.0.5 on 2020-04-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0040_itemwariant2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='rozmiar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
