# Generated by Django 3.0.5 on 2020-04-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0042_auto_20200422_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='rozmiar',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
