# Generated by Django 3.0.5 on 2020-04-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0045_item_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ilosc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
