# Generated by Django 3.0.5 on 2020-04-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0046_item_ilosc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='ilosc',
            field=models.IntegerField(blank=True, help_text='Jesli przedmiot nie posiada rozmiarowki, prosze podac tutaj ilosc', null=True),
        ),
    ]
