# Generated by Django 3.0.5 on 2020-04-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0047_auto_20200423_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='ilosc',
            field=models.IntegerField(blank=True, help_text='Jesli przedmiot nie posiada rozmiarowki lub innego wariantu, prosze podac tutaj ilosc', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.BooleanField(default=False, help_text='Jesli przedmiot posiada rozmiarowke lub inny wariant zaznacz pole'),
        ),
    ]
