# Generated by Django 3.0.5 on 2020-04-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0048_auto_20200423_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemwariant',
            name='kolejnosc',
            field=models.IntegerField(blank=True, help_text='Kolejnosc w ktorej sortowane beda rozmiary, a nastepnie wyswietlone na stronie. Zaczynamy od S = 1, m = 2 i tak dalej', null=True),
        ),
    ]
