# Generated by Django 3.0.5 on 2020-05-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0050_ocena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocena',
            name='ocena',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '2'), (4, '2'), (5, '2')], max_length=30),
        ),
    ]
