# Generated by Django 3.0.5 on 2020-05-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0052_auto_20200504_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocena',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
