# Generated by Django 3.0.5 on 2020-05-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0054_auto_20200505_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='zamowienie_w_realizacji',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(default=False, help_text='Jeśli zaznaczone na TAK, zamówienie zostało opłacone'),
        ),
    ]
