# Generated by Django 3.0.5 on 2020-05-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0055_auto_20200505_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocena',
            name='potwierdzona',
            field=models.BooleanField(default=False, help_text='Ustawi się na Tak jeśli oceniany przedmiot bedzie opłacony przez użytkownika'),
        ),
    ]
