# Generated by Django 3.0.5 on 2020-05-06 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0057_auto_20200506_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kategoria',
            old_name='titile',
            new_name='title',
        ),
    ]
