# Generated by Django 3.0.5 on 2020-05-07 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0060_auto_20200507_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='phone_number',
        ),
    ]
