# Generated by Django 3.0.5 on 2020-05-07 11:20

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0062_address_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
